laser_filter:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.5
        upper_threshold: 12.0
        lower_replacement_value: -.inf
        upper_replacement_value: .inf