rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/ttyUSB1
    serial_baudrate: 115200
    frame_id: laser
    inverted: false
    angle_compensate: true
    scan_mode: Standard
    scan_frequency: 5.0
