<?xml version="1.0"?>
<robot name="testbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find testbot_description)/urdf/physical_properties.xacro"/>
 
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
 
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
 
  <link name="base_footprint"/>
 
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${robot_length} ${robot_width} 0.04"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${robot_length} ${robot_width} 0.04"/>
      </geometry>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="${base_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${base_inertia_y}" iyz="0.0"
               izz="${base_inertia_z}"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} -${wheel_radius}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${wheel_inertia_y}" iyz="0.0"
               izz="${wheel_inertia_z}"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${wheel_separation/2} -${wheel_radius}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${wheel_inertia_y}" iyz="0.0"
               izz="${wheel_inertia_z}"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${robot_length/3} 0 -${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="caster">
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${caster_mass}"/>
      <inertia ixx="${caster_inertia}" ixy="0.0" ixz="0.0"
               iyy="${caster_inertia}" iyz="0.0"
               izz="${caster_inertia}"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0.0 0.0 0.08" rpy="0 0 0"/>  <!-- Adjust XYZ based on actual position -->
  </joint>

  <!-- RPLidar link -->
  <link name="laser">
    <visual>
      <geometry>
        <cylinder length="0.04" radius="0.025"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="0.025"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

</robot>
