/testbot_driver:
  ros__parameters:
    # Serial Communication
    serial_port: "/dev/ttyUSB0"
    baudrate: 115200
    timeout: 0.1

    # Motor Parameters
    left_motor:
      encoder_ticks_per_rev: 1440  # For N20 motor with encoder
      pid:
        kp: 0.1
        ki: 0.01
        kd: 0.05
      max_rpm: 100
      min_rpm: 10

    right_motor:
      encoder_ticks_per_rev: 1440
      pid:
        kp: 0.1
        ki: 0.01
        kd: 0.05
      max_rpm: 100
      min_rpm: 10

    # Robot Physical Parameters
    wheel_radius: 0.022  # meters
    wheel_separation: 0.13  # meters
    max_linear_speed: 0.5  # m/s
    max_angular_speed: 2.0  # rad/s

    # Update Frequencies
    command_timeout: 0.5  # seconds
    publish_frequency: 50.0  # Hz
    control_frequency: 50.0  # Hz

    