# config/control_params.yaml

/testbot_control:
  ros__parameters:
    # Controller update frequency
    control_frequency: 50.0  # Hz
    publish_frequency: 50.0  # Hz

    # Robot Physical Parameters
    wheel_radius: 0.022        # meters (44mm diameter)
    wheel_separation: 0.13     # meters (130mm)
    max_wheel_rpm: 100.0      # Maximum RPM of the motors
    encoder_resolution: 1440   # Encoder ticks per revolution

    # Speed Limits
    max_linear_speed: 0.5     # m/s
    max_angular_speed: 2.0    # rad/s
    min_linear_speed: 0.05    # m/s
    min_angular_speed: 0.1    # rad/s
    
    # Acceleration Limits
    linear_acceleration: 0.5   # m/s^2
    angular_acceleration: 1.0  # rad/s^2

    # PID Controllers
    linear_velocity_controller:
      kp: 1.0
      ki: 0.0
      kd: 0.0
      windup_limit: 1.0
      min_output: -1.0
      max_output: 1.0

    angular_velocity_controller:
      kp: 1.0
      ki: 0.0
      kd: 0.0
      windup_limit: 1.0
      min_output: -1.0
      max_output: 1.0

    # Odometry
    odom_frame: odom
    base_frame: base_footprint
    publish_tf: true
    enable_odom_tf: true
    
    # Command timeout
    cmd_vel_timeout: 0.5  # seconds
    
    # Velocity smoothing
    velocity_smoothing: true
    smoothing_factor: 0.2  # 0.0 to 1.0, lower = smoother

    # Teleoperation Settings
    teleop:
      linear_scaling: 1.0    # Scale factor for linear velocity commands
      angular_scaling: 1.0   # Scale factor for angular velocity commands
      linear_increment: 0.1  # Speed increment for key press
      angular_increment: 0.1 # Angular increment for key press